#!/usr/bin/env bash

# Extracting all broken hyperref detected by PDFTex
for file in "./main/acle.md" "./morello/morello.md" "./mve_intrinsics/mve.md" "./neon_intrinsics/advsimd.md"; do
  echo "Checking $file..."

  # The following string of pipes extracts the unresolved internal links by:
  # - Using the error and warning messages generated by pandoc pdf conversion as the first pipe input
  # - Using grep to extract all unresolved links, eg "pdfTeX warning (dest): name{ssec-bf16-scalar}"
  #   Note: Some broken links may be on mutiple lines. The -zoP flag is used to accomodate this. More info here:
  #   https://unix.stackexchange.com/a/361707
  # - Using sed to output all the warnings on separate lines to allow them to be counted
  # - Using wc to count all the lines and thus all the warnings/detected broken links
    number_of_broken_refs=`pandoc $file --verbose -o pdfs/tmp.pdf 2>&1 | \
                           grep -zoP 'pdfTeX warning \(dest\): name' | \
                           sed -E  's/name/\n/g' | wc -l`

  if [[ $number_of_broken_refs -gt 0 ]]; then
      echo "**** ERROR! There are $number_of_broken_refs unresolved internal references in $file."
      echo "Please use this command on your local terminal for more information:"
      echo "pandoc [md file] --verbose -o pdfs/tmp.pdf > [error output file]"
      exit 1
  fi
done
