#!/usr/bin/env bash

# Extracting all broken hyperref detected by PDFTex
for file in "./main/acle.md" "./morello/morello.md" "./mve_intrinsics/mve.md" "./neon_intrinsics/advsimd.md"; do
  echo "Checking $file..."

  # The following string of pipes extracts the unresolved internal links by:
  # - Using tee to output the error and warning messages generated by pandoc pdf conversion into a file
  # - Using grep to extract all unresolved links from the file, eg "pdfTeX warning (dest): name{ssec-bf16-scalar}"
  # - Using wc to count all the lines and thus all the warnings/detected broken links
  pandoc $file --verbose -o pdfs/tmp.pdf 2>&1 | tee output
  number_of_broken_refs=`cat output | grep 'pdfTeX warning (dest): name' | wc -l`

  if [[ $number_of_broken_refs -gt 0 ]]; then
      echo "**** ERROR! There are $number_of_broken_refs unresolved internal references in $file."
      echo "Please use this command on your local terminal for more information:"
      echo "pandoc $file --verbose -o pdfs/tmp.pdf"
      exit 1
  fi
done
