# SPDX-FileCopyrightText: Copyright 2021 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# SPDX-License-Identifier: Apache-2.0
name: CI

on: [push, pull_request]

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/ubuntu:24.04
    steps:
    - uses: actions/checkout@v6.0.2
    - name: check the correctness of the sources and generate the PDFs
      run: |
        # This is equivalent to the Dockerfile in tools/docker
        apt-get update \
        && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          texlive-latex-base \
          texlive-fonts-recommended \
          texlive-fonts-extra \
          texlive-latex-extra \
          lmodern \
          pandoc \
          inkscape \
          python3 \
          python3-tabulate \
          librsvg2-bin \
          nodejs

        # this is equivalent to the entrypoint of the Dockerfile in tools/docker

        # Check that the internal links in the markdown files are correct
        ./tools/hyperref-check.sh || exit 1

        # Recreate the full markdown files from the templates and check that the saved ones are consistent.
        ./tools/generate-intrinsics-specs.sh || exit 1
        
        ./tools/generate-pdfs.sh || exit 1
        
    - uses: actions/upload-artifact@v7
      with:
        name: pdfs
        path: pdfs

  build-github-pages:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/github/pages-gem:latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: generate the GitHub Pages locally in order to check for errors
      run:  |
        echo -e "plugins:\n \
          - jekyll-coffeescript\n \
          - jekyll-default-layout\n \
          - jekyll-gist\n \
          - jekyll-github-metadata\n \
          - jekyll-optional-front-matter\n \
          - jekyll-paginate\n \
          - jekyll-readme-index\n \
          - jekyll-titles-from-headings\n \
          - jekyll-relative-links\n" >> _config.yml
        SITE=.
        jekyll build

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: tcort/github-action-markdown-link-check@v1
      with:
          config-file: '.github/workflows/markdown-link-check.json'

  draftversion-check:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main' || github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
    - name: Check correctness of draftversion fields
      run:  python ./tools/acle_draftversion_value_check.py .
